#This is the build pipeline

trigger:
- master

pool:
  name: 'Local Device'

steps:
- script: echo Running on my on-premises device!
  displayName: 'Verify Runner Location'
# steps:
#   - task: UseNode@1
#     inputs:
#       checkLatest: true
#       force32bit: true

#   - script: |
#       npm install
#       npm run build
#     displayName: 'npm install and build'
    