#This is the build pipeline

trigger:
- master

jobs:
- job: BuildAndPublishArtifact
  pool:
    name: 'Local Device'

  steps:
  - script: |
      echo "The current user is: $USER"
      echo "The system PATH is: $PATH"
      echo "The agent working directory is: $AGENT_WORK_DIRECTORY"
    displayName: 'Verify Runner Location'

  - task: UseNode@1
    inputs:
      version: '24.16.0'
      force32bit: false

  # Installing Dependencies
  - script: npm install
    displayName: 'Install Dependencies'

  # Creating the Build
  - script: npm run build
    displayName: 'Creating the Build Artifact'

  # Saving the Artifact
  - task: PublishPipelineArtifact@1
    displayName: 'Publishing Artifact'
    inputs:
  #    targetPath: '$(Pipeline.Workspace)' //This the whole root directory. i.e. a, b, TestResults & s folder.
      targetPath: '$(System.DefaultWorkingDirectory)/docs'
      artifact: 'tetris-artifact'
      publishLocation: 'pipeline'